'use client';

import { 
  HiHome, 
  HiBell, 
  HiChartBar, 
  HiCube, 
  HiFolder, 
  HiShoppingCart, 
  HiUsers, 
  HiTag, 
  HiTicket, 
  HiGift, 
  HiDocument, 
  HiMenu, 
  HiPencil, 
  HiStar, 
  HiRefresh, 
  HiCreditCard,
  HiPhotograph,
  HiCollection,
  HiShoppingBag,
  HiChartPie,
  HiCash,
  HiTruck,
  HiUserGroup,
  HiGlobe
} from 'react-icons/hi';

export const MenuIcons = {
  home: HiHome,
  analytics: HiChartPie,
  notifications: HiBell,
  sales: HiChartBar,
  products: HiCube,
  categories: HiFolder,
  orders: HiShoppingCart,
  customers: HiUsers,
  discounts: HiTag,
  coupons: HiTicket,
  giftCards: HiGift,
  pages: HiDocument,
  navigation: HiMenu,
  blog: HiDocument,
  popups: HiCollection,
  media: HiPhotograph,
  bulkEdit: HiPencil,
  reviews: HiStar,
  returns: HiRefresh,
  storeCredits: HiCreditCard,
  abandonedCarts: HiShoppingBag,
  wishlist: HiBell,
  payments: HiCash,
  shipping: HiTruck,
  loyalty: HiUserGroup,
  webhooks: HiGlobe,
};

